### ISSUE TITLE
 TypeError: Cannot read property 'headersSent' of undefined

### ISSUE THREAD

**Issue by BienfaitM** [pillarjs/finalhandler#25] opened 2018-12-04 08:39 UTC
```
home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:256
  return typeof res.headersSent !== 'boolean'
                    ^

TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (/home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:256:21)
    at /home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:92:17
    at Function.handle (/home/bienfait/nodejs/Node-Express/node_modules/express/lib/application.js:170:5)
    at app (/home/bienfait/nodejs/Node-Express/node_modules/express/lib/express.js:39:9)
    at Object.<anonymous> (/home/bienfait/nodejs/Node-Express/index.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by dougwilson** [comment] 2019-01-29 22:50
Hi @BienfaitM , I believe this is a duplicate of #21 . That issue turned out to be an issue with the code that was written by the end user, and not an issue with this module.

If you can provide full code and steps to reproduce, I can re-open to look into the issue, but as far as I can tell from the stack trace, it's the same as #21

**Closed by dougwilson** 2019-01-29 22:50 UTC
