### ISSUE TITLE
UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)

### ISSUE THREAD

**Issue by williamd5** [pillarjs/finalhandler#37] opened 2021-09-13 15:54 UTC
The following line triggers an UnsupportedWarning when using Http2SecureServer from module http2.

https://github.com/pillarjs/finalhandler/blob/7ce018ca4364e1039426711253db458095980e59/index.js#L279

What can be done to avoid this when using the HTTP2 protocol?

```
(node:1002309) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)
    at statusMessageWarn (internal/http2/compat.js:100:13)
    at Http2ServerResponse.set statusMessage [as statusMessage] (internal/http2/compat.js:628:5)
    at Array.write (/home/project/node_modules/finalhandler/index.js:279:23)
    at listener (/home/project/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/project/node_modules/on-finished/index.js:100:5)
    at callback (/home/project/node_modules/ee-first/index.js:55:10)
    at Http2ServerRequest.onevent (/home/project/node_modules/ee-first/index.js:93:5)
    at Http2ServerRequest.emit (events.js:400:28)
    at Http2ServerRequest.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
```

**Comment by dougwilson** [comment] 2021-09-13 16:00
Duplicate of #34

**Closed by dougwilson** 2021-09-13 16:00 UTC
